version: '3.9'

services:
  webform:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: sh -c "sleep 20s ; python3 ./app.py"
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    volumes:
      - ./pdfFiles:/app/webform
